#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit"

echo -e "\n +-------------------------------------------------+"
echo -e " | post-commit hook execution                      |"

chmod -R 777 website/private/fantacalcio/777/ > /dev/null 2>&1

echo -e " | website/private/fantacalcio/777/ chmoded to 777 |"
echo -e " +-------------------------------------------------+\n\n"
