<?php
/*	array 8x15
				righe 	: 8 squadre
				colonne : 	0  - punti
							1  - differenza reti
							2  - goal fatti
							3  - nome
							4  - giocate
							5  - goal subiti
							6  - vinte
							7  - pareggiate
							8  - perse
							9  - fantapunti
							10 - fantamedia	
							11 - punti AA
							12 - punti AR	
							13 - punti RA
							14 - punti RR
							15 - percentuale punti guadagnati AA
							16 - percentuale punti guadagnati AR	
							17 - percentuale punti guadagnati RA
							18 - percentuale punti guadagnati RR	
							19 - link
*/							
							
$classifica[0][0]=0;
$classifica[0][1]=0;
$classifica[0][2]=0;
$classifica[0][3]=$a;
$classifica[0][4]=0;
$classifica[0][5]=0;
$classifica[0][6]=0;
$classifica[0][7]=0;
$classifica[0][8]=0;
$classifica[0][9]=0;
$classifica[0][10]=0;
$classifica[1][0]=0;
$classifica[1][1]=0;
$classifica[1][2]=0;
$classifica[1][3]=$b;
$classifica[1][4]=0;
$classifica[1][5]=0;
$classifica[1][6]=0;
$classifica[1][7]=0;
$classifica[1][8]=0;
$classifica[1][9]=0;
$classifica[1][10]=0;
$classifica[2][0]=0;
$classifica[2][1]=0;
$classifica[2][2]=0;
$classifica[2][3]=$c;
$classifica[2][4]=0;
$classifica[2][5]=0;
$classifica[2][6]=0;
$classifica[2][7]=0;
$classifica[2][8]=0;
$classifica[2][9]=0;
$classifica[2][10]=0;
$classifica[3][0]=0;
$classifica[3][1]=0;
$classifica[3][2]=0;
$classifica[3][3]=$d;
$classifica[3][4]=0;
$classifica[3][5]=0;
$classifica[3][6]=0;
$classifica[3][7]=0;
$classifica[3][8]=0;
$classifica[3][9]=0;
$classifica[3][10]=0;
$classifica[4][0]=0;
$classifica[4][1]=0;
$classifica[4][2]=0;
$classifica[4][3]=$e;
$classifica[4][4]=0;
$classifica[4][5]=0;
$classifica[4][6]=0;
$classifica[4][7]=0;
$classifica[4][8]=0;
$classifica[4][9]=0;
$classifica[4][10]=0;
$classifica[5][0]=0;
$classifica[5][1]=0;
$classifica[5][2]=0;
$classifica[5][3]=$f;
$classifica[5][4]=0;
$classifica[5][5]=0;
$classifica[5][6]=0;
$classifica[5][7]=0;
$classifica[5][8]=0;
$classifica[5][9]=0;
$classifica[5][10]=0;
$classifica[6][0]=0;
$classifica[6][1]=0;
$classifica[6][2]=0;
$classifica[6][3]=$g;
$classifica[6][4]=0;
$classifica[6][5]=0;
$classifica[6][6]=0;
$classifica[6][7]=0;
$classifica[6][8]=0;
$classifica[6][9]=0;
$classifica[6][10]=0;
$classifica[7][0]=0;
$classifica[7][1]=0;
$classifica[7][2]=0;
$classifica[7][3]=$h;
$classifica[7][4]=0;
$classifica[7][5]=0;
$classifica[7][6]=0;
$classifica[7][7]=0;
$classifica[7][8]=0;
$classifica[7][9]=0;
$classifica[7][10]=0;
$classifica[0][19]=real;
$classifica[1][19]=fedora;
$classifica[2][19]=patelavache;
$classifica[3][19]=lokomotiv;
$classifica[4][19]=bradipo;
$classifica[5][19]=atletico;
$classifica[6][19]=ciofeca;
$classifica[7][19]=eporediese;

?>