<?php
$shortName[0] = $shortName['a'] = 'ciofeca';
$shortName[1] = $shortName['b'] = 'real';
$shortName[2] = $shortName['c'] = 'patelavache';
$shortName[3] = $shortName['d'] = 'lokomotiv';
$shortName[4] = $shortName['e'] = 'eporediese';
$shortName[5] = $shortName['f'] = 'fedora';
$shortName[6] = $shortName['g'] = 'bradipo';
$shortName[7] = $shortName['h'] = 'atletico';

$longName[0] = $longName['a'] = 'Dinamo Ciofeca';
$longName[1] = $longName['b'] = 'Real Mentescars';
$longName[2] = $longName['c'] = 'Ij Patelavache';
$longName[3] = $longName['d'] = 'Lokomotiv Peccorino';
$longName[4] = $longName['e'] = 'EPOrediese';
$longName[5] = $longName['f'] = 'Fedora';
$longName[6] = $longName['g'] = 'Rapid Bradip';
$longName[7] = $longName['h'] = 'Atletico? No Grazie!';

$longName[$shortName['a']] = $longName['a'];
$longName[$shortName['b']] = $longName['b'];
$longName[$shortName['c']] = $longName['c'];
$longName[$shortName['d']] = $longName['d'];
$longName[$shortName['e']] = $longName['e'];
$longName[$shortName['f']] = $longName['f'];
$longName[$shortName['g']] = $longName['g'];
$longName[$shortName['h']] = $longName['h'];

$shortName[$longName['a']] = $shortName['a'];
$shortName[$longName['b']] = $shortName['b'];
$shortName[$longName['c']] = $shortName['c'];
$shortName[$longName['d']] = $shortName['d'];
$shortName[$longName['e']] = $shortName['e'];
$shortName[$longName['f']] = $shortName['f'];
$shortName[$longName['g']] = $shortName['g'];
$shortName[$longName['h']] = $shortName['h'];

$squadraJPG[0] = $squadraJPG['a'] = $squadraJPG[$shortName['a']] = $shortName['a'] . ".jpg";
$squadraJPG[1] = $squadraJPG['b'] = $squadraJPG[$shortName['b']] = $shortName['b'] . ".jpg";
$squadraJPG[2] = $squadraJPG['c'] = $squadraJPG[$shortName['c']] = $shortName['c'] . ".jpg";
$squadraJPG[3] = $squadraJPG['d'] = $squadraJPG[$shortName['d']] = $shortName['d'] . ".jpg";
$squadraJPG[4] = $squadraJPG['e'] = $squadraJPG[$shortName['e']] = $shortName['e'] . ".jpg";
$squadraJPG[5] = $squadraJPG['f'] = $squadraJPG[$shortName['f']] = $shortName['f'] . ".jpg";
$squadraJPG[6] = $squadraJPG['g'] = $squadraJPG[$shortName['g']] = $shortName['g'] . ".jpg";
$squadraJPG[7] = $squadraJPG['h'] = $squadraJPG[$shortName['h']] = $shortName['h'] . ".jpg";

$squadraXML[0] = $squadraXML['a'] = $squadraXML[$shortName['a']] = $shortName['a'] . ".xml";
$squadraXML[1] = $squadraXML['b'] = $squadraXML[$shortName['b']] = $shortName['b'] . ".xml";
$squadraXML[2] = $squadraXML['c'] = $squadraXML[$shortName['c']] = $shortName['c'] . ".xml";
$squadraXML[3] = $squadraXML['d'] = $squadraXML[$shortName['d']] = $shortName['d'] . ".xml";
$squadraXML[4] = $squadraXML['e'] = $squadraXML[$shortName['e']] = $shortName['e'] . ".xml";
$squadraXML[5] = $squadraXML['f'] = $squadraXML[$shortName['f']] = $shortName['f'] . ".xml";
$squadraXML[6] = $squadraXML['g'] = $squadraXML[$shortName['g']] = $shortName['g'] . ".xml";
$squadraXML[7] = $squadraXML['h'] = $squadraXML[$shortName['h']] = $shortName['h'] . ".xml";

$idxSquadra[$shortName[0]]=0;
$idxSquadra[$shortName[1]]=1;
$idxSquadra[$shortName[2]]=2;
$idxSquadra[$shortName[3]]=3;
$idxSquadra[$shortName[4]]=4;
$idxSquadra[$shortName[5]]=5;
$idxSquadra[$shortName[6]]=6;
$idxSquadra[$shortName[7]]=7;
?>
