<?php
	$localizer = "../../";
?>
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
	<title>Home | GENINATTI LAB</title>
	<?php require ($localizer . 'PI/Geninatti/includes/head_const_geninatti.php'); ?>
</head>
<body class="homepage">
	<div id="page-wrapper">

		<!-- Header -->
		<div id="header-wrapper">
			
			<!-- logo unito -->
			<a href="http://www.unito.it" title="University of Torino" target="_blank" id="unito-logo" style="text-decoration: none;">
			<div class="unito-logo-container">                   
	          </div></a>
	          
	          <a href="http://www.cim.unito.it" title="Molecular Imaging Center" target="_blank" style="text-decoration: none;" >
	          <div class="cim-logo-container">
	         </div></a>
			
			
			
			<div class="container">
					
				<!-- Header -->
				<header id="header" style="margin: -30px 0 30px 0;">
					<div class="inner">
					
						<!-- Logo -->
						<h1>
							<a href="<?php echo $localizer; ?>PI/Geninatti/home.php" id="logo">GENINATTI LAB</a>
							<div>
								<p style="color: gray; font-size=12px;" >Diagnostic protocols for imaging guided drug delivery and pathology assessment</p>


							</div>
						</h1>
						<!-- Nav -->
						<nav id="nav">
							<?php require ($localizer . 'PI/Geninatti/includes/menu_geninatti.php'); ?>
						</nav>

					</div>
				</header>

			</div>
		</div>


		<!-- Main Wrapper -->
		<div id="main-wrapper">

			<div class="wrapper style3">
				<div class="inner">
					<section class="container box feature3">
						<div class="row">

							<article>

								<h3 font style="text-transform: none;">Gadolinium/boron-based agents in imaging guided boron neutron capture therapy (BNCT)</h3>
								<p align="justify">A theranostic approach for the treatment of primary tumours and metastasis based on the use of Boron neutron 
								capture therapy (BNCT) that combines low energy neutron irradiation with the presence of boron-containing compound at the 
								targeted cells. The novel theranostic agents are able to maximize the selective uptake of boron atoms in tumour cells and, 
								at the same time, to quantify boron distribution in the tumour and in other tissues by MRI.</p>
							
								<div style="text-align: center;">
       							<img src="<?php echo $localizer; ?>PI/Geninatti/images/overview2.jpg" style="max-width: 50%; height: auto;" alt="FYI, image alt text is required" />
   							    </div>
								</article>
							<div class="4u 12u(mobile)">

								<!-- Spotlight -->
								<section>

									<article>

										<header>
											</br>
											<p font style="text-transform: none; font-size:1.3em">A theranostic approach based on the use of a dual boron/Gd agent 
											to improve the efficacy of Boron Neutron Capture Therapy in the lung cancer treatment.</p>
										</header>
										<img src="<?php echo $localizer; ?>PI/Geninatti/images/figureresearch21.jpg" alt="" class="image zooming">

										<p align="justify">
											This study aims at developing an innovative theranostic approach for lung tumor and metastases treatment, 
											based on Boron Neutron Capture Therapy (BNCT). It relies on to the use of low density lipoproteins (LDL) as 
											carriers able to maximize the selective uptake of boron atoms in tumor cells and, at the same time, to quantify 
											the in vivo boron distribution by magnetic resonance imaging (MRI). Tumor cells uptake was initially assessed by 
											ICP-MS and MRI on four types of tumor (TUBO, B16-F10, MCF-7, A549) and one healthy (N-MUG) cell lines. Lung metastases 
											were generated by intravenous injection of a Her2+ breast cancer cell line (i.e. TUBO) in BALB/c mice and transgenic 
											EML4-ALK mice were used as primary tumor model. After neutron irradiation, tumor growth was followed for 30-40 days 
											by MRI. Tumor masses of boron treated mice increased markedly slowly than the control group.
										</p>
										<img src="<?php echo $localizer; ?>PI/Geninatti/images/figureresearch21_b.jpg" alt="" class="image zooming">
										<a class="html" href="https://www.ncbi.nlm.nih.gov/pubmed/25596074"
												target="_blank"><font color="blue">D. Alberti et al, Nanomedicine: Nanotechnology, Biology, and Medicine 11 (2015) 741–750</font></a>

										
									</article>
								</section>
							</div>

							<div class="4u 12u(mobile)">

								<!-- Spotlight -->
								<section>

									<article>

										<header>
											<p font style="text-transform: none; font-size:1.3em">Theranostic Nanoparticles Loaded with Imaging Probes 
											and Rubrocurcumin for Combined Cancer Therapy by Folate Receptor Targeting. </p>
											
										</header>

										<p align="justify">
											The combination of different therapeutic modalities is a promising option to combat the recurrence of tumors. 
											In this study, polylactic and polyglycolic acid nanoparticles were used for the simultaneous delivery of a 
											boron–curcumin complex (RbCur) and an amphiphilic gadolinium complex into tumor cells with the aim of performing 
											boron and gadolinium neutron capture therapy (NCT) in conjunction with the additional antiproliferative effects 
											of curcumin. Furthermore, the use of Gd complexes allows magnetic resonance imaging (MRI) assessment of the amount 
											of B and Gd internalized by tumor cells. Poly(lactic-co-glycolic acid) (PLGA) nanoparticles were targeted to ovarian 
											cancer (IGROV-1) cells through folate receptors, by including in the formulation a PEGylated phospholipid 
											functionalized with the folate moiety. 
										</p>
										<img src="<?php echo $localizer; ?>PI/Geninatti/images/figureresearch22.jpg" alt="" class="image zooming">
										<p align="justify">NCT was performed on IGROV-1 cells internalizing 6.4 and 78.6 mgg1 of 10B and 157Gd, respectively. The synergic action of neutron 
										treatment and curcumin cytotoxicity was shown to result in a significant therapeutic improvement.</p>
										<a class="html" href="https://onlinelibrary.wiley.com/doi/pdf/10.1002/cmdc.201700039"
												target="_blank"><font color="blue">D. Alberti et al, ChemMedChem 2017, 12, 1 – 9</font></a>

										
									</article>
								</section>
							</div>

							<div class="4u 12u(mobile)">

								<!-- Spotlight -->
								<section>

									<article>

										<header>										
											<p font style="text-transform: none; font-size:1.3em">Synthesis of a carborane-containing cholesterol derivative and evaluation as a potential dual agent for MRI/BNCT applications. </p>
											<br>
										</header>
										<p align="justify">
										In this study the synthesis and characterization of a new dual, imaging and therapeutic, 
										agent is proposed with the aim of improving the efficacy of Boron Neutron Capture Therapy (BNCT) 
										in cancer treatment. The agent (Gd-B-AC01) consists of a carborane unit (ten boron atoms) 
										bearing a cholesterol unit on one side (to pursue the incorporation into the liposome bi-layer) 
										and a Gd(III)/1,4,7,10-tetraazacyclododecane
										monoamide complex on the other side (as a MRI reporter to attain the quantification of the B/Gd concentration). In order to endow 
										the BNCT agent with specific delivery properties, the liposome embedded
										with the MRI/BNCT dual probes has been functionalized with a pegylated phospholipid containing a folic acid residue at the end of 
										the PEG chain. The vector allows the binding of the liposome to folate receptors that are overexpressed in many tumor types, and in 
										particular, in human ovarian cancer cells (IGROV-1).
										<img src="<?php echo $localizer; ?>PI/Geninatti/images/figureresearch23.jpg" alt="" class="image zooming">											
										</p>
										<p align="justify">
										An in vitro test on IGROV-1 cells demonstrated that Gd-B-AC01 loaded liposomes are efficient carriers for
										the delivery of the MRI/BNCT probes to the tumor cells. Finally, the BNCT treatment of IGROV-1 cells
										showed that the number of surviving cells was markedly smaller when the cells were irradiated after
										internalization of the folate-targeted GdB10-AC01/liposomes.</p>

											
											<a class="html" href="https://pubs.rsc.org/en/content/articlelanding/2014/ob/c3ob42414f#!divAbstract"
												target="_blank"><font color="blue">D. Alberti et al, Org. Biomol. Chem., 2014, 12, 2457–2467</font></a>
										
							
										
										
									</article>
								</section>
							</div>

							


						</div>

					</section>

				</div>
			</div>
		</div>


	</div>

	<!-- Scripts -->

<?php require ($localizer . 'PI/includes/scripts.php'); ?>

</body>
</html>